version: '3.8'

services:
  report-service:
    user: "${USER_ID}:${GROUP_ID}"
    tty: true
    stdin_open: true
    build:
      context: .
      target: development
      args:
        NPM_AUTH_TOKEN: $NPM_AUTH_TOKEN
    container_name: report-service
    environment:
      NPM_AUTH_TOKEN: $NPM_AUTH_TOKEN
      PATH: /usr/src/app/node_modules/.bin:$PATH
    ports:
      - 3000:3000
      - 0.0.0.0:9300:9229
    volumes:
      - .:/usr/src/app:rw
    depends_on:
      - db
  db:
    image: postgres:12
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=report-service-dev,report-service-test
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    container_name: report-service-db
